apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dyffusion-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi  # Adjust based on your dataset size
  storageClassName: rook-ceph-block  # Change based on your cluster
